/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Empregado;
import classes.EmpregadoHorista;
import classes.EmpregadoMensalista;
import classes.Endereco;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import utilit.Utilit;

/**
 *
 * @author Alinda
 */
public class AppFolhaPgto extends javax.swing.JFrame {

    private Empregado empregado; //declaração

    public AppFolhaPgto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDadosPessoais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFTFCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFSobrenome = new javax.swing.JTextField();
        jPEndereco = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTFLogradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFBairro = new javax.swing.JTextField();
        jCBUf = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFTFCep = new javax.swing.JFormattedTextField();
        jTPTipoEmpregado = new javax.swing.JTabbedPane();
        jPEmpregadoMensalista = new javax.swing.JPanel();
        jCBCargo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPEmpregadoHorista = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSTotalHorasTrab = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jTFValorHora = new javax.swing.JTextField();
        jPDemonstrativoPgto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jPSalario = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTFSalarioBase = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTFSalarioLiquido = new javax.swing.JTextField();
        jPDescontos = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFInss = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTFIrpf = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Folha de Pagamento v. 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setText("Matrícula:");

        jTFMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel2.setText("CPF:");

        try {
            jFTFCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel3.setText("Nome:");

        jTFNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel4.setText("Sobrenome:");

        jTFSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        javax.swing.GroupLayout jPDadosPessoaisLayout = new javax.swing.GroupLayout(jPDadosPessoais);
        jPDadosPessoais.setLayout(jPDadosPessoaisLayout);
        jPDadosPessoaisLayout.setHorizontalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314)
                        .addComponent(jLabel2))
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTFSobrenome))
                .addContainerGap())
        );
        jPDadosPessoaisLayout.setVerticalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel5.setText("Tipo:");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Av.", "Rua", "Travessa" }));

        jLabel6.setText("Logradouro:");

        jTFLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel7.setText("No. Lt. Apt.");

        jTFNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel8.setText("Bairro:");

        jTFBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jCBUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "PR", "SP" }));

        jLabel9.setText("UF:");

        jLabel10.setText("Cidade:");

        jTFCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        jLabel11.setText("CEP:");

        try {
            jFTFCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AppFolhaPgto.this.focusLost(evt);
            }
        });

        javax.swing.GroupLayout jPEnderecoLayout = new javax.swing.GroupLayout(jPEndereco);
        jPEndereco.setLayout(jPEnderecoLayout);
        jPEnderecoLayout.setHorizontalGroup(
            jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEnderecoLayout.createSequentialGroup()
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCidade)
                    .addComponent(jTFBairro)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEnderecoLayout.createSequentialGroup()
                        .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 219, Short.MAX_VALUE))
                            .addComponent(jTFLogradouro)))
                    .addGroup(jPEnderecoLayout.createSequentialGroup()
                        .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTFNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFTFCep, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPEnderecoLayout.setVerticalGroup(
            jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCBCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador de Banco de Dados", "Analista de Sistemas", "Programador" }));

        jLabel12.setText("Cargo:");

        javax.swing.GroupLayout jPEmpregadoMensalistaLayout = new javax.swing.GroupLayout(jPEmpregadoMensalista);
        jPEmpregadoMensalista.setLayout(jPEmpregadoMensalistaLayout);
        jPEmpregadoMensalistaLayout.setHorizontalGroup(
            jPEmpregadoMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpregadoMensalistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPEmpregadoMensalistaLayout.setVerticalGroup(
            jPEmpregadoMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpregadoMensalistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPEmpregadoMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        jTPTipoEmpregado.addTab("Empregado Mensalista", jPEmpregadoMensalista);

        jLabel13.setText("Total de horas trabalhadas:");

        jSTotalHorasTrab.setModel(new SpinnerNumberModel(0,0,200,1));

        jLabel14.setText("Valor da Hora:");

        jTFValorHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFValorHoraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPEmpregadoHoristaLayout = new javax.swing.GroupLayout(jPEmpregadoHorista);
        jPEmpregadoHorista.setLayout(jPEmpregadoHoristaLayout);
        jPEmpregadoHoristaLayout.setHorizontalGroup(
            jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpregadoHoristaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSTotalHorasTrab, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jTFValorHora))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPEmpregadoHoristaLayout.setVerticalGroup(
            jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpregadoHoristaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jSTotalHorasTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEmpregadoHoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTPTipoEmpregado.addTab("Empregado Horista", jPEmpregadoHorista);

        jPDemonstrativoPgto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Demonstrativo de Pagamento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        jTAResultado.setEditable(false);
        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        jPSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salário:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel15.setText("Salário Base:");

        jTFSalarioBase.setEditable(false);

        jLabel16.setText("Salário Líquido:");

        jTFSalarioLiquido.setEditable(false);

        javax.swing.GroupLayout jPSalarioLayout = new javax.swing.GroupLayout(jPSalario);
        jPSalario.setLayout(jPSalarioLayout);
        jPSalarioLayout.setHorizontalGroup(
            jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalarioLayout.createSequentialGroup()
                .addGroup(jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFSalarioBase)
                    .addComponent(jTFSalarioLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPSalarioLayout.setVerticalGroup(
            jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTFSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTFSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPDescontos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descontos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel17.setText("INSS:");

        jTFInss.setEditable(false);

        jLabel18.setText("IRPF:");

        jTFIrpf.setEditable(false);

        javax.swing.GroupLayout jPDescontosLayout = new javax.swing.GroupLayout(jPDescontos);
        jPDescontos.setLayout(jPDescontosLayout);
        jPDescontosLayout.setHorizontalGroup(
            jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDescontosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFInss, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jTFIrpf))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPDescontosLayout.setVerticalGroup(
            jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDescontosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTFInss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTFIrpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPDemonstrativoPgtoLayout = new javax.swing.GroupLayout(jPDemonstrativoPgto);
        jPDemonstrativoPgto.setLayout(jPDemonstrativoPgtoLayout);
        jPDemonstrativoPgtoLayout.setHorizontalGroup(
            jPDemonstrativoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPDemonstrativoPgtoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPDemonstrativoPgtoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPDescontos, jPSalario});

        jPDemonstrativoPgtoLayout.setVerticalGroup(
            jPDemonstrativoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDemonstrativoPgtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPDemonstrativoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDescontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/calculator.png"))); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.GIF"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPTipoEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(jBLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSair)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPDemonstrativoPgto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCalcular, jBLimpar, jBSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPTipoEmpregado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPDemonstrativoPgto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCalcular)
                    .addComponent(jBLimpar)
                    .addComponent(jBSair))
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCalcular, jBLimpar, jBSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFValorHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFValorHoraKeyTyped
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != '.') {
            // getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTFValorHoraKeyTyped

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(new Color(184, 207, 229));

        }

    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_focusLost

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        if (jTFMatricula.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo matrícula", 
                                                                  "Aviso", 0);
            jTFMatricula.setText(null);
            jTFMatricula.requestFocusInWindow();
            return;
        }
        if (jTFNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo nome", 
                                                                  "Aviso", 0);
            jTFNome.setText(null);
            jTFNome.requestFocusInWindow();
            return;
        }
        if (jTFSobrenome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo sobrenome",
                    "Aviso", 0);
            jTFSobrenome.setText(null);
            jTFSobrenome.requestFocusInWindow();
            return;
        }

        String campoSemMasc = Utilit.removeMasc(jFTFCpf.getText());

        if (campoSemMasc.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha o campo CPF", 
                                                                  "SisFolhaPgto 1.0", 0);
            jFTFCpf.requestFocusInWindow();
            return;
        }

        String tipoLogradouro = "", uf = "";
        if (jCBTipo.getSelectedIndex() != -1) {
            tipoLogradouro = jCBTipo.getSelectedItem().toString();
            if (jTFLogradouro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o campo logradouro", 
                                                                      "SisFolhaPgto 1.0", 0);
                jTFLogradouro.requestFocusInWindow();
                return;
            }
        }

        if (jCBUf.getSelectedIndex() != -1) {
            uf = jCBUf.getSelectedItem().toString();
        }
        //fazer demais consistências

        Endereco endereco = new Endereco(tipoLogradouro + " " + 
                              jTFLogradouro.getText(), jTFNumero.getText(), jTFBairro.getText(), 
                              jTFCidade.getText(), uf, jFTFCep.getText().trim());

        if (jTPTipoEmpregado.getSelectedIndex() == 0) {
            if (jCBCargo.getSelectedIndex() != -1) {
                empregado = new EmpregadoMensalista(jCBCargo.getSelectedItem().toString(), 
                                   jTFMatricula.getText(), jTFNome.getText(), jTFSobrenome.getText(),
                                  jFTFCpf.getText(), endereco);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cargo para o empregado", 
                                                                     "SisFolhaPgto 1.0", 0);
                return;
            }
        } else if (jTPTipoEmpregado.getSelectedIndex() == 1) {
            int hora = (Integer) (jSTotalHorasTrab.getValue());
            if (hora == 0) {
                JOptionPane.showMessageDialog(this, "Preencha o campo 'Total de horas'", 
                                                                      "SisFolhaPgto 1.0", 0);
                jSTotalHorasTrab.requestFocusInWindow();
                return;
            }

            if (jTFValorHora.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o campo valor da hora", 
                                                                     "SisFolhaPgto 1.0", 0);
                jTFValorHora.requestFocusInWindow();
                return;
            }

            float valorHora = Float.parseFloat(jTFValorHora.getText());
            
            empregado = new EmpregadoHorista(jTFMatricula.getText(), 
                                  jTFNome.getText(), jTFSobrenome.getText(), jFTFCpf.getText(), 
                                  endereco, hora, valorHora);
        }//EmpregadoHorista

        DecimalFormat mascaraNum = new DecimalFormat("R$ #,##0.00");
        jTAResultado.setText(empregado.dados());
        jTFSalarioBase.setText(mascaraNum.format(empregado.getSalario()));
        jTFSalarioLiquido.setText(mascaraNum.format(empregado.calculaSalarioLiquido()));
        jTFInss.setText(mascaraNum.format(empregado.calculaInss()));
        jTFIrpf.setText(mascaraNum.format(empregado.calculaIR()));

    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        limpar();
    }//GEN-LAST:event_formWindowOpened

    private void limpar() {
        limpaCampos(jPDadosPessoais);
        limpaCampos(jPEndereco);
        jTAResultado.setText(null);
        limpaCampos(jPSalario);
        limpaCampos(jPDescontos);
        limpaCampos(jPEmpregadoHorista);
        limpaCampos(jPEmpregadoMensalista);
        jTFMatricula.requestFocusInWindow();
    }

    private void limpaCampos(javax.swing.JPanel painel) {
        java.awt.Component[] componentes = painel.getComponents();
        for (int i = 0; i < componentes.length; i++) {
            if (componentes[i] instanceof javax.swing.JTextField) {
                javax.swing.JTextField campo = (javax.swing.JTextField) componentes[i];
                campo.setText(null);
            }

            if (componentes[i] instanceof javax.swing.JComboBox) {
                javax.swing.JComboBox combo = (javax.swing.JComboBox) componentes[i];
                combo.setSelectedIndex(-1);
            }

            if (componentes[i] instanceof javax.swing.JSpinner) {
                javax.swing.JSpinner campoSpinner = (javax.swing.JSpinner) componentes[i];
                campoSpinner.setValue(0);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFolhaPgto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFolhaPgto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFolhaPgto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFolhaPgto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFolhaPgto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox<String> jCBCargo;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JComboBox<String> jCBUf;
    private javax.swing.JFormattedTextField jFTFCep;
    private javax.swing.JFormattedTextField jFTFCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDadosPessoais;
    private javax.swing.JPanel jPDemonstrativoPgto;
    private javax.swing.JPanel jPDescontos;
    private javax.swing.JPanel jPEmpregadoHorista;
    private javax.swing.JPanel jPEmpregadoMensalista;
    private javax.swing.JPanel jPEndereco;
    private javax.swing.JPanel jPSalario;
    private javax.swing.JSpinner jSTotalHorasTrab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFInss;
    private javax.swing.JTextField jTFIrpf;
    private javax.swing.JTextField jTFLogradouro;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFSalarioBase;
    private javax.swing.JTextField jTFSalarioLiquido;
    private javax.swing.JTextField jTFSobrenome;
    private javax.swing.JTextField jTFValorHora;
    private javax.swing.JTabbedPane jTPTipoEmpregado;
    // End of variables declaration//GEN-END:variables
}
